services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kigm_merch_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "9001:5432"

  admin_panel:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000" # Expose port 8000 to the host
    command: python -m uvicorn web.app:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*' --log-level debug
    # Port 8000 is exposed internally to other services, but not to the host

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    command: python main.py

volumes:
  db_data:
